apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
  namespace: fluxcd-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      type: loadbalancer
  template:
    metadata:
      labels:
        type: loadbalancer
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

