apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: default
spec:
  selector:
    app: loadbalanced
  type: LoadBalancer
  ports:
  - name: loadbalanced
    protocol: TCP
    port: 80
    targetPort: 80 
